### ISSUE TITLE
declare -ga SSHARGS gives error

### ISSUE THREAD

**Issue by razzius** [IngoMeyer441/sshrc#1]
~ 16:39 $ sshrc superset-staging
/usr/local/bin/sshrc: line 75: declare: -g: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
^C⏎
~ 16:39 $ bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)
Copyright (C) 2007 Free Software Foundation, Inc.

I fixed this locally by removing the `-g` from the `sshrc` script:
```diff
-  declare -ga SSHARGS
+  declare -a SSHARGS
```

**Comment by IngoMeyer441** [comment]
Thanks for pointing me to this. I forgot that macOS ships an old Bash version... And thanks for your PR (#2)!

**Comment by IngoMeyer441** [comment]
Fixed in 4616c25177d5c788f18241b16bb3f6d614dfd040.
